import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareOrder,authorizeWrite,markSubmitting,recordOrderOutcome} from '../scripts/workflow.mjs';
const context={storeCode:'S',beCode:'BE',orderType:1,beType:1,dataSource:'real'};
const plan=()=>({hardConstraintsSatisfied:true,verifiedTotalFen:2000,extraFeesFen:0,couponUse:[],items:[{productCode:'A',quantity:1}],calculatedAt:new Date().toISOString(),pricingContext:context,verificationKey:'official-confirmed-key',warnings:[]});
test('T16 no writes without explicit current-turn confirmation bound to summary',()=>{const s=prepareOrder(plan(),context);assert.equal(authorizeWrite('create-order',s,{}),false);assert.equal(authorizeWrite('create-order',s,{explicit:true,currentTurn:true,action:'create_order',digest:s.digest}),true);s.summary.totalFen=3000;assert.equal(authorizeWrite('create-order',s,{explicit:true,currentTurn:true,action:'create_order',digest:s.digest}),false);assert.equal(authorizeWrite('auto-bind-coupons',null,{explicit:true,action:'claim_coupons'}),false);});
test('T17 unknown create-order outcome blocks retries and requires query',()=>{const s=markSubmitting(prepareOrder(plan(),context)),unknown=recordOrderOutcome(s,{timeout:true});assert.equal(unknown.state,'unknown');assert.equal(unknown.nextAction,'query-order');assert.equal(unknown.retryAllowed,false);assert.equal(authorizeWrite('create-order',unknown,{explicit:true}),false);assert.throws(()=>markSubmitting(unknown),/DUPLICATE_ORDER_BLOCKED/);});
test('changed context, delivery address, stale price and mock orders blocked',()=>{assert.throws(()=>prepareOrder(plan(),{...context,storeCode:'OTHER'}),/REPRICE_REQUIRED/);assert.throws(()=>prepareOrder({...plan(),calculatedAt:'2020-01-01T00:00:00Z'},context),/REPRICE_REQUIRED/);assert.throws(()=>prepareOrder({...plan(),warnings:['MOCK_DATA']},context),/ORDER_BLOCKED/);const c={...context,orderType:2,beType:2,fulfillmentRef:'ADDR_1'},p={...plan(),pricingContext:c};assert.throws(()=>prepareOrder(p,c,{fulfillmentRef:'ADDR_2'}),/REPRICE_REQUIRED/);});
test('success creation never asserts paid; repeated submit not allowed',()=>{const s=markSubmitting(prepareOrder(plan(),context));assert.equal(authorizeWrite('create-order',s,{explicit:true}),false);const out=recordOrderOutcome(s,{success:true,orderId:'MOCK_ORDER'});assert.equal(out.state,'created');assert.equal(out.paymentState,'not_confirmed');});
